rewrite test

diff --git a/test b/test
--- a/test
+++ b/test
@@ -1,10 +1,18 @@
 #!/bin/bash
 
-VSM="./vsm"
 
-if [ ! -e "$VSM" ]; then
-	echo "vsm does not exist."
-else
-	"$VSM"
-fi
+while IFS='=' read exp ans 
+do 
+	retval=$(echo $(echo "$exp;" | ./vsm ))
+	ans=$(echo "$ans" | cut -d " " -f 2)
 
+	echo -n "retval = $retval, ans = $ans"
+
+	if [ "$retval" -eq "$ans" ] ; then
+		echo -e "\033[32m ok \033[m"
+	else
+		echo -e "\033[31m test failed \033[m" >&2
+	fi
+
+
+done < expressions
