rewrite tests

diff --git a/tests/test b/tests/test
--- a/tests/test
+++ b/tests/test
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 
-vsm="./vsm"
+vsm="../vsm"
 
 
 if ! [ -e "$vsm" ]; then
@@ -10,18 +10,21 @@ if ! [ -e "$vsm" ]; then
 fi
 
 
-while IFS=',' read exp ans 
-do 
-	retval=$(echo "$exp" | $vsm)
-	ans=$(echo "$ans" | cut -d " " -f 2)
-
-	echo -n "retval = $retval, ans = $ans"
-
-	if [ "$retval" -eq "$ans" ] ; then
-		echo -e "\033[32m ok \033[m"
-	else
-		echo -e "\033[31m test failed \033[m" >&2
-	fi
+diff <(cat assgn.test | $vsm) assgn.right
+if [ "$?" = 0 ];then
+	echo -n "[assgn test]"
+	echo -e "\033[32m ok \033[m"
+else
+	echo -n "[assgn test]"
+	echo -e "\033[31m test failed. \033[m"
+fi
 
 
-done < expressions
+diff <(cat calc.test | $vsm) calc.right
+if [ "$?" = 0 ];then
+	echo -n "[calc test]"
+	echo -e "\033[32m ok \033[m"
+else
+	echo -n "[calc test]"
+	echo -e "\033[31m test failed. \033[m"
+fi
